In [3]:
import numpy as np

#EX#1
#crit. Sylvester ne spune CAND putem aplica Metoda Gauss
#crit. Sylvester: vf o matrice e pozitiv definita => vf. ca toti minorii principali sunt inversabili
def MEGFP(A, b):
    U = np.copy(A)
    n = np.shape(A)[0]
    assert A[0,0] != 0, "A nu e pozitiv definita"
    for k in range (1,n):
        #ne folosim de vectorizare si de slicing pentru a decupa minorii
        #ex. minor de ordin 2: A[:2, :2]
        #folosim o functie suplimentara ptc exista pb la calculul det (cand tinde la zero)
        assert ~np.isclose(np.linalg.det(A[:k+1, :k+1]), 0), "A nu e pozitiv definita"
    for k in range (0,n-1):
        for i in range (k+1, n):
            #facem zero pe pozitia (i,k)
            m = U[i][k] / U[k][k]
            U[i, k:] -= m * U[k, k:] #tehnica de vectorizare
            #general advice: optimizati codul, scapati de mai cat mai multe for-uri
            b[i] -= m * b[k]
    return U, b

#calculul solutiilor
def subs_desc(U,b):
    assert np.shape(U)[0]==np.shape(U)[1],"U nu este patratica"
    n = np.shape(U)[0]
    x = np.ones((n,1))*float("nan")
    x[n-1] = b[n-1]/ U[n-1, n-1]
    for k in range (n-2,-1,-1):
        s = 0
        for j in range (k+1, n):
            s = s+ U[k,j]*x[j]
            x[k] = (b[k]- s)/U[k,k]
    return x

#a)
A_a = np.array([[3, 5, 3],[2, 2, 3],[-1, -3, 0]]).astype(float)
b_a = np.array([1, 3, 2]).astype(float)
#U1, b1 = MEGFP(A_a, b_a) #aici da o eroare, presupun ca, dat fiind ca nu avem matrice pozitiv definita, nu putem aplica Metoda Gauss Fara Pivotare
#print(U1, b1) #aici da un AssertionError pentru ca nu e pozitiv definita

#d)
A_d = np.array([[1, 2, 1],[2, 2, 3],[-1, -3, 1]]).astype(float)
b_d = np.array([0, 3, 3]).astype(float)
U2, b2 = MEGFP(A_d, b_d)
print(U2, b2)
x = subs_desc(U2,b2)
print(x)
#calcul determinant: print(np.linalg.det(A))

#b) Eroare: TypeError: 'type' object is not subscriptable
'''
for k1 in range [1,11]:
    print("Pentru k = ", k1)
    e = 10**((-2)*k1)
    A_k1 = np.array([[e, 1],[1, 1]]).astype(float)
    b_k1 = np.array([1+e, 2]).astype(float)
    U_k1, b_k1 = MEGFP(A_k1, b_k1)
    print(U_k1, b_k1)
    x_k1 = subs_desc(U_k1, b_k1)
    print(x_k1)
'''
#c)
A_c = np.array([[10**(-12), 1, -1], [40, -60, 0], [3, -4, 5]]).astype(float)
b_c = np.array([17 + 10**(-12), -1160, -62]).astype(float)
U4, b4 = MEGFP(A_c, b_c)
print(U4, b4)
x = subs_desc(U4,b4)
print(x)

[[ 1.   2.   1. ]
 [ 0.  -2.   1. ]
 [ 0.   0.   1.5]] [0.  3.  1.5]
[[ 1.]
 [-1.]
 [ 1.]]
[[ 1.00000000e-12  1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00 -4.00000000e+13  4.00000000e+13]
 [ 0.00000000e+00 -4.88281250e-04  5.50048828e+00]] [ 1.70000000e+01 -6.80000000e+14  1.64921875e+01]
[[ 0.99831254]
 [19.99831336]
 [ 2.99831336]]


In [13]:
#EX#2
def MEGPP(A, b):
    U = np.copy(A)
    n = np.shape(A)[0]
    assert A[0,0] != 0, "A nu e pozitiv definita"
    dim = U.shape
    print(dim)
    for k in range (1,n):
        assert ~np.isclose(np.linalg.det(A[:k+1, :k+1]), 0), "A nu e pozitiv definita"
    for k in range (0,n-1):
        l = 0
        for i in range(k, n+1):
            if U[i][k] > l:
                l = U[i][k]
        for i in range (k+1, n):
            m = U[i][k] / U[k][k]
            U[i, k:] -= m * U[k, k:] #tehnica de vectorizare
            #general advice: optimizati codul, scapati de mai cat mai multe for-uri
            b[i] -= m * b[k]
    return U, b

#a)
A_2_a = np.array([[2, 6, 6], [1, 2, 3], [1, 4, 3]]).astype(float)
b_2_a = np.array([14, 6, 8]).astype(float)
#U_2_a, b_a = MEGPP(A_2_a, b_2_a)
#print(U_2_a, b_a) #iar da eroare, nu avem matrice pozitiv definita

#b)
A_2_b = np.array([[2, 6, 6], [1, 2, 3]]).astype(float)
b_2_b = np.array([14, 6]).astype(float)
U_2_b, b_b = MEGPP(A_2_b, b_2_b)
print(U_2_b, b_b)
x_2_b = subs_desc(U_2_b, b_b) #nu putem calcula solutie, deoarece nu avem matrice patratica??
print(x_2_b)

#c)
A_2_c = np.array([[2, 6, 6], [1, 2, 3], [1, 4, 3]])
b_2_c = np.array([14, 6, 8, 3]).astype(float)
U_2_c, b_c = MEGPP(U_2_c, b_c)
print(U_2_c, b_c)
x_2_c = subs_desc(U_2_c, b_c)
print(x_2_c)

#d)

(2, 3)


IndexError: index 2 is out of bounds for axis 0 with size 2